name: Deploy to Github Pages

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Build with npm
        run: |
          cd ./web
          npm ci
          npm run build --if-present
      - name: Deploy using gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/mickelsonmichael/JustPickSomething.git
          cd ./web
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
